version: "3.9"
services:
  feed:
    build: package-feeds
    ports:
      - 8080:8080
    environment: 
      - OSSMALWARE_TOPIC_URL=kafka://packages
      - KAFKA_BROKERS=kafka:9092
    depends_on:
        - kafka
  cron:
    build: scheduler
    depends_on:
        - feed
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181:2181'
    # volumes:
    #   - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
      - '9092:9092'
    # volumes:
    #   - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
